default:
  file:         "default.csv"
  dataset:      Low
  jitter:       TRUE
  statslogging: TRUE
  showtarget:   FALSE
  targetreturn: 1.07
  short:        20
  medium:       50
  long:         200
  current:      0.00
  currshares:   1
  originalcb:   0.00
  origshares:   0
